[metadata]
name = smart_robot
version = 0.1.0
description = ROS 2 modular robot communication system
long_description = file: README.md
long_description_content_type = text/markdown
author = Swayam44
license = MIT

[options]
packages = find:
install_requires =
    setuptools
    rclpy
    std_msgs
    std_srvs

[options.package_data]
* = *.launch.py

[options.extras_require]

[options.entry_points]
console_scripts =
    sensor_node = smart_robot.sensor_node:main
    controller_node = smart_robot.controller_node:main
    battery_node = smart_robot.battery_node:main
    monitor_node = smart_robot.monitor_node:main
    robot_control_service = smart_robot.control_node:main

[bdist_wheel]
universal = 1
